/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lmsfinal;

import com.formdev.flatlaf.FlatLightLaf;
import java.awt.Color;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.ZoneId;
import java.util.Calendar;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import java.time.temporal.ChronoUnit;

/**
 *
 * @author testing101
 */
public class frmcheckout extends javax.swing.JFrame{


    public frmcheckout() {
        
        setVisible(false);
        initComponents();
        lblTitle.setText(REUSABLES.strngBook);
        lblIsbn.setText(REUSABLES.strngIsbn);
        
        lblRecTitle.setVisible(false);
        lblRecIsbn.setVisible(false);
        lblRecQuant.setVisible(false);
        lblRecBorName.setVisible(false);
        lblDayHand.setVisible(false);
        lblDayOver.setVisible(false);
        lblServFee.setVisible(false);
        lblBookFee.setVisible(false);
        lblOverFee.setVisible(false);
        lblTotalFee.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        lblIsbn = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        lblTotalFee = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        cmbQuant = new javax.swing.JComboBox<>();
        txtBorName = new javax.swing.JTextField();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jDateChooser3 = new com.toedter.calendar.JDateChooser();
        jButton1 = new javax.swing.JButton();
        lblTitle = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        lblRecTitle = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblRecIsbn = new javax.swing.JLabel();
        lblRecQuant = new javax.swing.JLabel();
        lblRecBorName = new javax.swing.JLabel();
        lblDayHand = new javax.swing.JLabel();
        lblDayOver = new javax.swing.JLabel();
        lblServFee = new javax.swing.JLabel();
        lblBookFee = new javax.swing.JLabel();
        lblOverFee = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(55, 2, 2));
        jPanel1.setPreferredSize(new java.awt.Dimension(600, 400));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("CHECKOUT");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 116, -1));

        jPanel6.setBackground(new java.awt.Color(255, 255, 153));
        jPanel6.setPreferredSize(new java.awt.Dimension(631, 2));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 631, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 70, -1, -1));

        jLabel18.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel18.setForeground(java.awt.Color.white);
        jLabel18.setText("Quantity:");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 140, -1));

        lblIsbn.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblIsbn.setForeground(java.awt.Color.white);
        lblIsbn.setText("isbn string");
        jPanel1.add(lblIsbn, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 110, -1));

        jLabel20.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel20.setForeground(java.awt.Color.white);
        jLabel20.setText("ISBN:");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 50, -1));

        jLabel21.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel21.setForeground(java.awt.Color.white);
        jLabel21.setText("Date Received:");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 140, -1));

        jLabel22.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel22.setForeground(java.awt.Color.white);
        jLabel22.setText("Borrower's Name:");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 140, -1));

        jLabel23.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel23.setForeground(java.awt.Color.white);
        jLabel23.setText("Date Borrowed:");
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 140, -1));

        jLabel24.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel24.setForeground(java.awt.Color.white);
        jLabel24.setText("Date Due:");
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 140, -1));

        lblTotalFee.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblTotalFee.setForeground(new java.awt.Color(51, 51, 51));
        lblTotalFee.setText("TOTAL");
        jPanel1.add(lblTotalFee, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 360, 110, -1));

        jLabel26.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(51, 51, 51));
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setText("RECEIPT");
        jLabel26.setToolTipText("");
        jPanel1.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 90, 110, -1));

        cmbQuant.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4" }));
        jPanel1.add(cmbQuant, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, -1, -1));

        txtBorName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBorNameActionPerformed(evt);
            }
        });
        jPanel1.add(txtBorName, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, 120, -1));

        jDateChooser1.setFocusable(false);
        jPanel1.add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 280, 150, -1));
        jPanel1.add(jDateChooser2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 310, 150, -1));
        jPanel1.add(jDateChooser3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, 150, -1));

        jButton1.setText("Generate Receipt");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, -1, -1));

        lblTitle.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblTitle.setForeground(java.awt.Color.white);
        lblTitle.setText("book string");
        jPanel1.add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 110, -1));

        jLabel28.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel28.setForeground(java.awt.Color.white);
        jLabel28.setText("Book:");
        jPanel1.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 50, -1));

        jLabel29.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel29.setForeground(java.awt.Color.white);
        jLabel29.setText("Book:");
        jPanel1.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 50, -1));

        jLabel30.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(51, 51, 51));
        jLabel30.setText("Days in Hand:");
        jPanel1.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 220, 130, -1));

        jLabel31.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(51, 51, 51));
        jLabel31.setText("Book:");
        jPanel1.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 120, 50, -1));

        lblRecTitle.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblRecTitle.setForeground(new java.awt.Color(51, 51, 51));
        lblRecTitle.setText("book");
        jPanel1.add(lblRecTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 120, 110, -1));

        jLabel33.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(51, 51, 51));
        jLabel33.setText("ISBN:");
        jPanel1.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 140, 50, -1));

        jLabel34.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(51, 51, 51));
        jLabel34.setText("Quantity: ");
        jPanel1.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 170, 70, -1));

        jLabel35.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(51, 51, 51));
        jLabel35.setText("Borrower's Name:");
        jPanel1.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 190, 130, -1));

        jLabel36.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(51, 51, 51));
        jLabel36.setText("Overdue Fee");
        jPanel1.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 340, 130, -1));

        jLabel37.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(51, 51, 51));
        jLabel37.setText("Days Overdue:");
        jPanel1.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 250, 130, -1));

        jLabel38.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(51, 51, 51));
        jLabel38.setText("Fees:");
        jPanel1.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 280, 130, -1));

        jLabel39.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(51, 51, 51));
        jLabel39.setText("Service Fee");
        jPanel1.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 300, 130, -1));

        jLabel40.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(51, 51, 51));
        jLabel40.setText("Book Fee");
        jPanel1.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 320, 130, -1));

        jSeparator1.setForeground(new java.awt.Color(51, 51, 51));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 360, 100, 10));

        lblRecIsbn.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblRecIsbn.setForeground(new java.awt.Color(51, 51, 51));
        lblRecIsbn.setText("isbn");
        jPanel1.add(lblRecIsbn, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 140, 110, -1));

        lblRecQuant.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblRecQuant.setForeground(new java.awt.Color(51, 51, 51));
        lblRecQuant.setText("1");
        jPanel1.add(lblRecQuant, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 170, 110, -1));

        lblRecBorName.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblRecBorName.setForeground(new java.awt.Color(51, 51, 51));
        lblRecBorName.setText("hell yea");
        jPanel1.add(lblRecBorName, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 190, 110, -1));

        lblDayHand.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblDayHand.setForeground(new java.awt.Color(51, 51, 51));
        lblDayHand.setText("date");
        jPanel1.add(lblDayHand, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 220, 110, -1));

        lblDayOver.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblDayOver.setForeground(new java.awt.Color(51, 51, 51));
        lblDayOver.setText("date");
        jPanel1.add(lblDayOver, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 250, 110, -1));

        lblServFee.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblServFee.setForeground(new java.awt.Color(51, 51, 51));
        lblServFee.setText("P0");
        jPanel1.add(lblServFee, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 300, 110, -1));

        lblBookFee.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblBookFee.setForeground(new java.awt.Color(51, 51, 51));
        lblBookFee.setText("P0");
        jPanel1.add(lblBookFee, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 320, 110, -1));

        lblOverFee.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblOverFee.setForeground(new java.awt.Color(51, 51, 51));
        lblOverFee.setText("P0");
        jPanel1.add(lblOverFee, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 340, 110, -1));

        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/receipt1.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 80, 310, 320));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtBorNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBorNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBorNameActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        lblRecTitle.setVisible(true);
        lblRecIsbn.setVisible(true);
        lblRecQuant.setVisible(true);
        lblRecBorName.setVisible(true);
        lblDayHand.setVisible(true);
        lblDayOver.setVisible(true);
        lblServFee.setVisible(true);
        lblBookFee.setVisible(true);
        lblOverFee.setVisible(true);
        lblTotalFee.setVisible(true);
        
        lblRecTitle.setText(lblTitle.getText());
        lblRecIsbn.setText(lblIsbn.getText());
        lblRecQuant.setText(String.valueOf(cmbQuant.getSelectedItem()));
        lblRecBorName.setText(txtBorName.getText());
                
    }//GEN-LAST:event_jButton1ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try{
            UIManager.setLookAndFeel(new FlatLightLaf());
        }catch(UnsupportedLookAndFeelException ex){
            System.err.println("Failed to initialize LaF");
        }
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmcheckout().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbQuant;
    private javax.swing.JButton jButton1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private com.toedter.calendar.JDateChooser jDateChooser3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblBookFee;
    private javax.swing.JLabel lblDayHand;
    private javax.swing.JLabel lblDayOver;
    private javax.swing.JLabel lblIsbn;
    private javax.swing.JLabel lblOverFee;
    private javax.swing.JLabel lblRecBorName;
    private javax.swing.JLabel lblRecIsbn;
    private javax.swing.JLabel lblRecQuant;
    private javax.swing.JLabel lblRecTitle;
    private javax.swing.JLabel lblServFee;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTotalFee;
    private javax.swing.JTextField txtBorName;
    // End of variables declaration//GEN-END:variables
}
