/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lmsfinal;

import com.formdev.flatlaf.FlatLightLaf;
import java.awt.Color;
import java.time.ZoneId;
import java.util.Calendar;
import java.util.concurrent.TimeUnit;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.table.DefaultTableModel;
import java.util.ArrayList;

/**
 *
 * @author testing101
 */
public class frmcheckout extends javax.swing.JFrame{


    public frmcheckout() {
        
        setVisible(false);
        initComponents();
        
        
        listBook.setModel(REUSABLES.modelBook);
        listBook.setSelectedIndex(0);
        
        lblRecBorName.setVisible(false);
        lblDayHand.setVisible(false);
        lblDayOver.setVisible(false);
        lblServFee.setVisible(false);
        lblBookFee.setVisible(false);
        lblOverFee.setVisible(false);
        lblTotalFee.setVisible(false);
        
        
        tblRec.setModel(tableModell);
        
        for (int i=0; i<REUSABLES.arrBook.size();i++)  {
            tableModell.addRow(new Object[]{REUSABLES.arrBook.get(i), REUSABLES.arrIsbn.get(i), "1"});
        }
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        lblTotalFee = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        cmbQuant = new javax.swing.JComboBox<>();
        txtBorName = new javax.swing.JTextField();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jDateChooser3 = new com.toedter.calendar.JDateChooser();
        jButton1 = new javax.swing.JButton();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblRecBorName = new javax.swing.JLabel();
        lblDayHand = new javax.swing.JLabel();
        lblDayOver = new javax.swing.JLabel();
        lblServFee = new javax.swing.JLabel();
        lblBookFee = new javax.swing.JLabel();
        lblOverFee = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listBook = new javax.swing.JList<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRec = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(55, 2, 2));
        jPanel1.setPreferredSize(new java.awt.Dimension(600, 450));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("CHECKOUT");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 116, -1));

        jPanel6.setBackground(new java.awt.Color(255, 255, 153));
        jPanel6.setPreferredSize(new java.awt.Dimension(631, 2));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 631, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 70, -1, -1));

        jLabel18.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel18.setForeground(java.awt.Color.white);
        jLabel18.setText("Quantity:");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 140, -1));

        jLabel21.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel21.setForeground(java.awt.Color.white);
        jLabel21.setText("Date Received:");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 140, -1));

        jLabel22.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel22.setForeground(java.awt.Color.white);
        jLabel22.setText("Borrower's Name:");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 140, -1));

        jLabel23.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel23.setForeground(java.awt.Color.white);
        jLabel23.setText("Date Borrowed:");
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 140, -1));

        jLabel24.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel24.setForeground(java.awt.Color.white);
        jLabel24.setText("Date Due:");
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 140, -1));

        lblTotalFee.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblTotalFee.setForeground(new java.awt.Color(51, 51, 51));
        lblTotalFee.setText("TOTAL");
        jPanel1.add(lblTotalFee, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 390, 110, -1));

        jLabel26.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(51, 51, 51));
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setText("RECEIPT");
        jLabel26.setToolTipText("");
        jPanel1.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 100, 110, -1));

        cmbQuant.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4" }));
        cmbQuant.setToolTipText("Select the book's title then adjust the book's quantity");
        cmbQuant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbQuantActionPerformed(evt);
            }
        });
        jPanel1.add(cmbQuant, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, -1, -1));

        txtBorName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBorNameActionPerformed(evt);
            }
        });
        jPanel1.add(txtBorName, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, 120, -1));

        jDateChooser1.setFocusable(false);
        jPanel1.add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 270, 150, -1));
        jPanel1.add(jDateChooser2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 300, 150, -1));
        jPanel1.add(jDateChooser3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 330, 150, -1));

        jButton1.setText("Generate Receipt");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, -1, -1));

        jLabel28.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel28.setForeground(java.awt.Color.white);
        jLabel28.setText("Book:");
        jPanel1.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 50, -1));

        jLabel29.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel29.setForeground(java.awt.Color.white);
        jLabel29.setText("Book:");
        jPanel1.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 50, -1));

        jLabel30.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(51, 51, 51));
        jLabel30.setText("Days in Hand:");
        jPanel1.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 280, 130, -1));

        jLabel35.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(51, 51, 51));
        jLabel35.setText("Borrower's Name:");
        jPanel1.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 260, 130, -1));

        jLabel36.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(51, 51, 51));
        jLabel36.setText("Overdue Fee");
        jPanel1.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 360, 130, 20));

        jLabel37.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(51, 51, 51));
        jLabel37.setText("Days Overdue:");
        jPanel1.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 300, 130, -1));

        jLabel38.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(51, 51, 51));
        jLabel38.setText("Fees:");
        jPanel1.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 320, 130, -1));

        jLabel39.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(51, 51, 51));
        jLabel39.setText("Service Fee");
        jPanel1.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 370, 130, 20));

        jLabel40.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(51, 51, 51));
        jLabel40.setText("Books Fee");
        jPanel1.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 340, 130, 20));

        jSeparator1.setForeground(new java.awt.Color(51, 51, 51));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 390, 100, 10));

        lblRecBorName.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblRecBorName.setForeground(new java.awt.Color(51, 51, 51));
        lblRecBorName.setText("name");
        jPanel1.add(lblRecBorName, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 260, 110, -1));

        lblDayHand.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblDayHand.setForeground(new java.awt.Color(51, 51, 51));
        lblDayHand.setText("date");
        jPanel1.add(lblDayHand, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 280, 170, -1));

        lblDayOver.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblDayOver.setForeground(new java.awt.Color(51, 51, 51));
        lblDayOver.setText("date");
        jPanel1.add(lblDayOver, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 300, 160, -1));

        lblServFee.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblServFee.setForeground(new java.awt.Color(51, 51, 51));
        lblServFee.setText("P0");
        jPanel1.add(lblServFee, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 379, 110, 10));

        lblBookFee.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblBookFee.setForeground(new java.awt.Color(51, 51, 51));
        lblBookFee.setText("P0");
        jPanel1.add(lblBookFee, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 340, 110, -1));

        lblOverFee.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblOverFee.setForeground(new java.awt.Color(51, 51, 51));
        lblOverFee.setText("P0");
        jPanel1.add(lblOverFee, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 360, 110, -1));

        listBook.setOpaque(false);
        listBook.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listBookMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                listBookMouseReleased(evt);
            }
        });
        jScrollPane2.setViewportView(listBook);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 170, 80));

        tblRec.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblRec);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 130, 270, 120));

        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/receipt1.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 90, 310, 320));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 437, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtBorNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBorNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBorNameActionPerformed

    
    private DefaultTableModel  tableModell = new DefaultTableModel(new String[]{"Book Title", "ISBN", "Quantity"}, 0);
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        java.util.Date date1=jDateChooser1.getDate();
        java.util.Date date2=jDateChooser2.getDate();
        java.util.Date date3=jDateChooser3.getDate();
        
        
        lblRecBorName.setVisible(true);
        lblDayHand.setVisible(true);
        lblDayOver.setVisible(true);
        lblServFee.setVisible(true);
        lblBookFee.setVisible(true);
        lblOverFee.setVisible(true);
        lblTotalFee.setVisible(true);
        
        
        lblRecBorName.setText(txtBorName.getText());
        lblDayHand.setText(Long.toString(TimeUnit.DAYS.convert(date3.getTime() - date1.getTime(), TimeUnit.MILLISECONDS)));
        lblDayOver.setText(Long.toString(TimeUnit.DAYS.convert(date3.getTime() - date2.getTime(), TimeUnit.MILLISECONDS)));
        
        if(Integer.parseInt(lblDayOver.getText())<0){
            lblDayOver.setText("0");
        }
        
        ArrayList<Integer> arrQuant = new ArrayList<>(REUSABLES.arrBook.size());
        
        double bookFee=0;
        for(int i=0; i<REUSABLES.arrBook.size();i++){
            bookFee+=40*Integer.valueOf((String) tblRec.getValueAt(i, 2));
        }
        
        double servFee=5;
        double overFee=bookFee* Integer.parseInt(lblDayOver.getText()) * 0.5;
        double totalFee=servFee+bookFee+overFee;
        
        lblServFee.setText("P" + Double.toString(servFee));
        lblBookFee.setText("P" + Double.toString(bookFee));
        lblOverFee.setText("P" + Double.toString(overFee));
        lblTotalFee.setText("P" + Double.toString(totalFee));
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cmbQuantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbQuantActionPerformed
        tblRec.setValueAt(cmbQuant.getSelectedItem(), listBook.getSelectedIndex(), 2);
    }//GEN-LAST:event_cmbQuantActionPerformed

    private void listBookMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listBookMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_listBookMouseClicked

    private void listBookMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listBookMouseReleased
        
    }//GEN-LAST:event_listBookMouseReleased
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try{
            UIManager.setLookAndFeel(new FlatLightLaf());
        }catch(UnsupportedLookAndFeelException ex){
            System.err.println("Failed to initialize LaF");
        }
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmcheckout().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbQuant;
    private javax.swing.JButton jButton1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private com.toedter.calendar.JDateChooser jDateChooser3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblBookFee;
    private javax.swing.JLabel lblDayHand;
    private javax.swing.JLabel lblDayOver;
    private javax.swing.JLabel lblOverFee;
    private javax.swing.JLabel lblRecBorName;
    private javax.swing.JLabel lblServFee;
    private javax.swing.JLabel lblTotalFee;
    private javax.swing.JList<String> listBook;
    private javax.swing.JTable tblRec;
    private javax.swing.JTextField txtBorName;
    // End of variables declaration//GEN-END:variables
}
