package lmsfinal;
import java.sql.ResultSet;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Driver;
import java.util.logging.Level;
import java.util.logging.Logger;


public class pnlaccount extends javax.swing.JPanel {
    
    int choice= 0;
    public pnlaccount() {
        initComponents();
        pnlchange.setVisible(false);
        reread();
        clear();
        
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel18 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        bttnchangeusername = new javax.swing.JButton();
        bttnchangepassword = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        pnlchange = new javax.swing.JPanel();
        flabel2 = new javax.swing.JLabel();
        flabel1 = new javax.swing.JLabel();
        ffield1 = new javax.swing.JTextField();
        ffield2 = new javax.swing.JTextField();
        fbuttonchange = new javax.swing.JButton();
        fname = new javax.swing.JLabel();
        fusername = new javax.swing.JLabel();
        fpassword = new javax.swing.JLabel();
        femail = new javax.swing.JLabel();

        setBackground(new java.awt.Color(55, 2, 2));
        setForeground(java.awt.Color.white);
        setMinimumSize(new java.awt.Dimension(790, 520));
        setPreferredSize(new java.awt.Dimension(790, 520));
        setLayout(null);

        jLabel18.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel18.setForeground(java.awt.Color.white);
        jLabel18.setText("Password: ");
        add(jLabel18);
        jLabel18.setBounds(71, 179, 115, 19);

        jPanel6.setBackground(new java.awt.Color(255, 255, 153));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 690, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        add(jPanel6);
        jPanel6.setBounds(48, 77, 690, 2);

        jLabel16.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel16.setForeground(java.awt.Color.white);
        jLabel16.setText("ACCOUNT DETAILS");
        add(jLabel16);
        jLabel16.setBounds(48, 37, 210, 23);

        jLabel19.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel19.setForeground(java.awt.Color.white);
        jLabel19.setText("Username:");
        add(jLabel19);
        jLabel19.setBounds(70, 148, 115, 19);

        bttnchangeusername.setBackground(new java.awt.Color(165, 36, 34));
        bttnchangeusername.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        bttnchangeusername.setForeground(java.awt.Color.white);
        bttnchangeusername.setText("CHANGE USERNAME");
        bttnchangeusername.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bttnchangeusername.setBorderPainted(false);
        bttnchangeusername.setVerifyInputWhenFocusTarget(false);
        bttnchangeusername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnchangeusernamebttnsignupActionPerformed(evt);
            }
        });
        add(bttnchangeusername);
        bttnchangeusername.setBounds(550, 140, 154, 25);

        bttnchangepassword.setBackground(new java.awt.Color(165, 36, 34));
        bttnchangepassword.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        bttnchangepassword.setForeground(java.awt.Color.white);
        bttnchangepassword.setText("CHANGE PASSWORD");
        bttnchangepassword.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bttnchangepassword.setBorderPainted(false);
        bttnchangepassword.setVerifyInputWhenFocusTarget(false);
        bttnchangepassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnchangepasswordbttnsignupActionPerformed(evt);
            }
        });
        add(bttnchangepassword);
        bttnchangepassword.setBounds(550, 180, 154, 25);

        jLabel20.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel20.setForeground(java.awt.Color.white);
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel20.setText("Full Name:");
        add(jLabel20);
        jLabel20.setBounds(71, 256, 115, 19);

        jLabel21.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel21.setForeground(java.awt.Color.white);
        jLabel21.setText("Email:");
        add(jLabel21);
        jLabel21.setBounds(71, 219, 115, 19);

        pnlchange.setBackground(new java.awt.Color(78, 2, 2));

        flabel2.setForeground(java.awt.Color.white);
        flabel2.setToolTipText("");

        flabel1.setForeground(java.awt.Color.white);

        ffield1.setBackground(java.awt.Color.white);
        ffield1.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        ffield1.setForeground(java.awt.Color.black);

        ffield2.setBackground(java.awt.Color.white);
        ffield2.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        ffield2.setForeground(java.awt.Color.black);

        fbuttonchange.setBackground(new java.awt.Color(165, 36, 34));
        fbuttonchange.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        fbuttonchange.setForeground(java.awt.Color.white);
        fbuttonchange.setText("CHANGE PASSWORD");
        fbuttonchange.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        fbuttonchange.setBorderPainted(false);
        fbuttonchange.setVerifyInputWhenFocusTarget(false);
        fbuttonchange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fbuttonchangebttnsignupActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlchangeLayout = new javax.swing.GroupLayout(pnlchange);
        pnlchange.setLayout(pnlchangeLayout);
        pnlchangeLayout.setHorizontalGroup(
            pnlchangeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlchangeLayout.createSequentialGroup()
                .addGroup(pnlchangeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlchangeLayout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addGroup(pnlchangeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(flabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                            .addComponent(flabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(47, 47, 47)
                        .addGroup(pnlchangeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ffield1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ffield2, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlchangeLayout.createSequentialGroup()
                        .addGap(205, 205, 205)
                        .addComponent(fbuttonchange, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(139, Short.MAX_VALUE))
        );
        pnlchangeLayout.setVerticalGroup(
            pnlchangeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlchangeLayout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addGroup(pnlchangeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(flabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ffield1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlchangeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(flabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ffield2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(fbuttonchange)
                .addGap(22, 22, 22))
        );

        add(pnlchange);
        pnlchange.setBounds(70, 320, 640, 170);

        fname.setForeground(java.awt.Color.white);
        add(fname);
        fname.setBounds(170, 260, 270, 20);

        fusername.setForeground(java.awt.Color.white);
        add(fusername);
        fusername.setBounds(170, 150, 220, 20);

        fpassword.setForeground(java.awt.Color.white);
        add(fpassword);
        fpassword.setBounds(170, 180, 220, 20);

        femail.setForeground(java.awt.Color.white);
        add(femail);
        femail.setBounds(170, 220, 220, 20);
    }// </editor-fold>//GEN-END:initComponents
    public void reread(){
     
        String qry = "SELECT username, password, email, name FROM tbl_accounts WHERE username = ?";

        try (Connection con = DB.open(); PreparedStatement preparedStatement = con.prepareStatement(qry)) {

            preparedStatement.setString(1, GV.MAINUSERNAME);

            try (ResultSet rs = preparedStatement.executeQuery()) {
                while (rs.next()) {
                    String username = rs.getString("username");
                    String password = rs.getString("password");
                    String email = rs.getString("email");
                    String name = rs.getString("name");

                    fusername.setText(username);
                    fpassword.setText(password);
                    femail.setText(email);
                    fname.setText(name);

                }
            } catch (SQLException e) {
                e.printStackTrace();
            }

        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }
    private void bttnchangeusernamebttnsignupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnchangeusernamebttnsignupActionPerformed
        pnlchange.setVisible(true);
        choice(1);
          
    }//GEN-LAST:event_bttnchangeusernamebttnsignupActionPerformed

    private void bttnchangepasswordbttnsignupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnchangepasswordbttnsignupActionPerformed
       pnlchange.setVisible(true);
       choice(2);
    }//GEN-LAST:event_bttnchangepasswordbttnsignupActionPerformed

    private void fbuttonchangebttnsignupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fbuttonchangebttnsignupActionPerformed
      if(ffield1.getText() == ffield2.getText()){
          if (choice == 1) {
            if (REUSABLES.checkNotNull(ffield1.getText(), ffield2.getText())) {
                String qry = "UPDATE tbl_accounts SET username = '" + ffield1.getText()
                        + "' WHERE username = '" + GV.MAINUSERNAME + "'";
                DB.executeQuery(qry);
                 REUSABLES.showNotif("Account updated successfully!");
                 GV.MAINUSERNAME = ffield1.getText();
                 clear();
                 pnlchange.setVisible(false);
                 reread();
                 
            }
            else{
                REUSABLES.showNotif("Answer all Fields");
            }
        }
     
        if (choice==2){
             if (REUSABLES.checkNotNull(ffield1.getText(), ffield2.getText())) {
                String qry = "UPDATE tbl_accounts SET password = '" + ffield2.getText() + "' WHERE username = '" + GV.MAINUSERNAME + "'";
                DB.executeQuery(qry);
                 REUSABLES.showNotif("Account updated successfully!");
                GV.MAINPASSWORD = ffield1.getText();
                  clear();
                 pnlchange.setVisible(false);
                 reread();

            }
            else{
                REUSABLES.showNotif("Answer all Fields");
            }
        }
      }else{
          REUSABLES.showNotif("INPUT DOES NOT MATCH!");
      }
      
      
    }//GEN-LAST:event_fbuttonchangebttnsignupActionPerformed
    
    private void choice(int choice){
        if (choice ==1){
            flabel1.setText("Set new Username: ");
            flabel2.setText("Confirm new Username: ");
            fbuttonchange.setText("CHANGE USERNAME");
        }
        if (choice==2){
             fbuttonchange.setText("CHANGE PASSWORD");
              flabel1.setText("Set new Password: ");
            flabel2.setText("Confirm new Password: ");
        }
    }
    
    private void clear(){
        ffield1.setText(null);
        ffield2.setText(null);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttnchangepassword;
    private javax.swing.JButton bttnchangeusername;
    private javax.swing.JButton fbuttonchange;
    private javax.swing.JLabel femail;
    private javax.swing.JTextField ffield1;
    private javax.swing.JTextField ffield2;
    private javax.swing.JLabel flabel1;
    private javax.swing.JLabel flabel2;
    private javax.swing.JLabel fname;
    private javax.swing.JLabel fpassword;
    private javax.swing.JLabel fusername;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel pnlchange;
    // End of variables declaration//GEN-END:variables
}
